const hollandPairAdvices: Record<string, string> = {
  RI: 'Bạn là người kết hợp giữa thực tiễn và tư duy phân tích. Điều này khiến bạn không chỉ giỏi trong việc vận hành thiết bị, máy móc, mà còn có khả năng tìm hiểu nguyên lý hoạt động sâu xa đằng sau nó. Bạn sẽ phù hợp với các lĩnh vực như công nghệ kỹ thuật, kỹ sư điện tử, lập trình hệ thống nhúng, hoặc nghiên cứu phát triển sản phẩm. Hãy học cách vừa rèn luyện kỹ năng thực hành, vừa đầu tư phát triển tư duy khoa học để phát triển toàn diện.',
  RA: 'Bạn vừa có tính thực tế, vừa có thiên hướng nghệ thuật – một sự kết hợp hiếm có. Điều này cho thấy bạn có thể làm tốt trong các lĩnh vực thiết kế công nghiệp, kỹ thuật ứng dụng vào mỹ thuật, kiến trúc nội thất, hoặc sáng tạo sản phẩm vật lý. Hãy theo đuổi những ngành cho phép bạn làm việc bằng tay và đồng thời thể hiện gu thẩm mỹ cá nhân.',
  RS: 'Sự kết hợp giữa khả năng thực hành và lòng trắc ẩn giúp bạn phù hợp với các nghề mang tính xã hội nhưng vẫn cần thao tác tay nghề, như vật lý trị liệu, y học phục hồi chức năng, kỹ thuật viên chăm sóc sức khỏe. Bạn nên tìm đến những môi trường có tính cộng đồng, nơi bạn có thể vừa làm việc hiệu quả, vừa giúp đỡ người khác.',
  RE: 'Bạn có tính hướng ngoại và khả năng thực hành tốt, điều này rất phù hợp để theo đuổi những công việc như kỹ thuật viên tư vấn, hướng dẫn kỹ thuật bán hàng, hoặc quản lý sản xuất. Bạn thích giải quyết vấn đề thực tiễn và có tố chất lãnh đạo đội nhóm. Hãy tìm môi trường nơi bạn có thể vừa ra quyết định, vừa thấy thành quả rõ ràng.',
  RC: 'Bạn có xu hướng tổ chức tốt và tỉ mỉ trong công việc thực tế. Đây là nền tảng lý tưởng để theo đuổi các công việc như kỹ thuật viên lập kế hoạch sản xuất, quản lý kho, hay kiểm định kỹ thuật. Bạn nên trau dồi thêm các kỹ năng tổ chức, sử dụng phần mềm kỹ thuật, để kết hợp tốt giữa năng lực thực hành và quản trị.',
  IA: 'Bạn có trí tuệ phân tích và óc sáng tạo – sự kết hợp tuyệt vời để nghiên cứu hoặc phát triển ý tưởng trong lĩnh vực khoa học nghệ thuật, công nghệ truyền thông, hoặc thiết kế tương tác. Hãy phát triển cả tư duy phản biện và kỹ năng thể hiện cảm xúc, điều này sẽ đưa bạn xa hơn trong các ngành như thiết kế UX, data visualization, hoặc khoa học ứng dụng.',
  IS: 'Sự kết hợp giữa đầu óc phân tích và lòng nhân hậu khiến bạn trở thành chuyên gia lý tưởng trong các lĩnh vực như tâm lý học, tư vấn giáo dục, hoặc nghiên cứu xã hội. Bạn có khả năng tiếp cận vấn đề một cách hệ thống, nhưng vẫn giữ được sự đồng cảm và thấu hiểu con người. Hãy tìm đến những công việc giúp bạn khai thác cả hai mặt này.',
  IE: 'Bạn thông minh, quyết đoán và có khả năng lãnh đạo trong môi trường khoa học, kỹ thuật. Hãy hướng đến vị trí trưởng nhóm nghiên cứu, quản lý sản phẩm công nghệ, hoặc khởi nghiệp trong lĩnh vực công nghệ cao. Bạn phù hợp với công việc đòi hỏi ra quyết định dựa trên dữ liệu và kiến thức sâu.',
  IC: 'Bạn là người kỹ lưỡng, thích sự chính xác, phù hợp với những ngành khoa học ứng dụng như thống kê, kiểm toán khoa học, kỹ thuật viên phân tích dữ liệu. Hãy phát triển kỹ năng lập trình, xử lý dữ liệu lớn và phần mềm chuyên dụng để nâng cao giá trị bản thân.',
  AS: 'Bạn có tâm hồn nghệ sĩ nhưng cũng giàu lòng nhân ái. Bạn sẽ tỏa sáng trong các lĩnh vực như trị liệu nghệ thuật, giáo dục sáng tạo, hoạt động cộng đồng. Hãy tận dụng khả năng kết nối cảm xúc của mình để truyền cảm hứng và chữa lành cho người khác thông qua nghệ thuật.',
  AE: 'Bạn là người sáng tạo và dám thể hiện. Nghề nghiệp lý tưởng cho bạn là truyền thông, marketing sáng tạo, nghệ sĩ biểu diễn hoặc người làm nội dung. Bạn có khả năng thuyết phục người khác bằng cảm xúc và hình ảnh. Hãy học thêm kỹ năng quản lý dự án để hiện thực hóa ý tưởng của mình.',
  AC: 'Bạn là người vừa tỉ mỉ, vừa có thẩm mỹ – thích hợp với thiết kế in ấn, trình bày dữ liệu trực quan, thiết kế giao diện phần mềm. Bạn cần không gian làm việc yên tĩnh, chuyên nghiệp nhưng vẫn có cơ hội thể hiện bản sắc cá nhân. Tính tổ chức sẽ giúp bạn làm nghệ thuật một cách hiệu quả.',
  SE: 'Bạn là người có kỹ năng giao tiếp xuất sắc và giàu lòng nhân ái. Hãy theo đuổi các ngành như tư vấn hướng nghiệp, huấn luyện kỹ năng mềm, quản lý nhân sự hoặc tổ chức sự kiện giáo dục. Bạn phát triển mạnh mẽ trong môi trường có sự kết nối và giá trị cộng đồng.',
  SC: 'Bạn là người chăm chỉ, đáng tin cậy và luôn muốn giúp đỡ đúng cách. Hãy theo đuổi các công việc hành chính, thư ký trong ngành giáo dục, y tế, hoặc phi lợi nhuận. Bạn là người đứng sau hỗ trợ nhưng đóng vai trò quan trọng không thể thay thế.',
  EC: 'Bạn kết hợp tư duy hệ thống và năng lực lãnh đạo. Đây là nền tảng cho những vị trí như quản lý dự án, kiểm toán viên trưởng, trưởng phòng hành chính. Bạn có thể trở thành người xây dựng cấu trúc, tổ chức và định hướng phát triển bền vững cho doanh nghiệp hoặc tổ chức.'
};

export default hollandPairAdvices;
